[phases.setup]
nixPkgs = ["...", "python311Packages.supervisor"]

[phases.build]
cmds = [
    "mkdir -p /etc/supervisor/conf.d/",
    "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
    "cp /assets/supervisord.conf /etc/supervisord.conf",
    "chmod +x /assets/start.sh"
]

[start]
cmd = '/assets/start.sh'

[staticAssets]
"start.sh" = '''
#!/bin/bash

# Generate Caddyfile from a template
node /assets/scripts/prestart.mjs /assets/Caddyfile.template /etc/Caddyfile

# Start Supervisor (which starts PHP-FPM & Caddy)
supervisord -c /etc/supervisord.conf -n
'''

"supervisord.conf" = '''
[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/assets/supervisord.pid
nodaemon=false
silent=false
minfds=1024
minprocs=200

[include]
files = /etc/supervisor/conf.d/*.conf
'''

"worker-caddy.conf" = '''
[program:worker-caddy]
command=caddy run --config /etc/Caddyfile --adapter caddyfile
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-caddy.log
stderr_logfile=/var/log/worker-caddy.log
'''

"worker-phpfpm.conf" = '''
[program:worker-phpfpm]
command=php-fpm -y /assets/php-fpm.conf -F
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-phpfpm.log
stderr_logfile=/var/log/worker-phpfpm.log
'''

"worker-laravel.conf" = '''
[program:worker-laravel]
command=bash -c 'exec php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600'
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=12
startsecs=0
stopwaitsecs=3600
stdout_logfile=/var/log/worker-laravel.log
stderr_logfile=/var/log/worker-laravel.log
'''

"php-fpm.conf" = '''
[www]
listen = 127.0.0.1:9000
user = www-data
group = www-data
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 50
pm.min_spare_servers = 4
pm.max_spare_servers = 32
pm.start_servers = 18
clear_env = no
'''

"Caddyfile.template" = '''
{
    auto_https off
    log {
        output file /var/log/caddy-access.log
    }
}

:80 {
    root * /app/public
    php_fastcgi 127.0.0.1:9000
    file_server
}
'''
